### ISSUE TITLE
Forecasts for both directions

### ISSUE THREAD

**Issue by volives** [martinp/atbapi#1]
How can one request bus departures from a given stopId (bus direction)?

The resquest 
_/api/v1/departures/{node-id}_
seems to return the results for an arbitrary direction for that node-id. 

Thank you!

**Comment by thordy** [comment]
Each node only returns buses going in one direction

e.g. 
```
# Nova Kinosenter towards Downtown
https://atbapi.tar.io/api/v1/departures/16011022

# Nova Kinosenter from Downtown
https://atbapi.tar.io/api/v1/departures/16010022
```

Notice how the `nodeId`s are almost the same `16011022` vs `16010022`, this is how most stops behave, where one is towards downtown, and the other out of downtown

**Comment by volives** [comment]
Great.  Yes, that was my mistake. Thank you!
